### PR TITLE
feat: add zkSync Era Mainnet and Testnet chains

### PR DESCRIPTION
**Pull request by nick8319**
Add support for zkSync Era Mainnet and Testnet chains

-------------------------

**Edit by Germán:**
Blockers:
- https://github.com/safe-global/safe-deployments/issues/251
- https://github.com/safe-global/safe-deployments/issues/252
- New release of `safe-deployments`.

### CODE REVIEW

**Comment by nick8319** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nick8319** [comment]
recheck

**Comment by germartinez** [comment]
Hi @nick8319,
I saw you created this GitHub issue as well: https://github.com/safe-global/safe-deployments/issues/252

The `protocol-kit` depends on the `safe-deployments` package. Before we can include this change, a new release of the `safe-deployments` needs to be published. When that happens all the `safe-deployments` dependencies should be updated in this PR as well.

Thank you.

**Comment by nick8319** [comment]
Hi @germartinez 
It was included into v1.25.0 and this PR is updated.

**Comment by germartinez** [comment]
Thank you for your Pull Request, sorry for recreate it [here](https://github.com/safe-global/safe-core-sdk/pull/479) but there was one missing network in this one and it was faster for me to recreate it. We are releasing the Protocol Kit today.

Thanks again!

**Pull request closed without merging**
