### PR TITLE
 chore: add short name 970 OORT Mainnet #1 

### PR DESCRIPTION
**Pull request by molecula451**
## What it solves
Resolves #

## How this PR fixes it

Add name for new deployment, ref https://github.com/safe-global/safe-deployments/pull/813

### CODE REVIEW

**Comment by molecula451** [comment]
recheck

**Comment by molecula451** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by molecula451** [comment]
recheck

**Comment by molecula451** [comment]
recheck

**Comment by dasanra** [comment]
Solved in #1017

**Pull request closed without merging**
