### PR TITLE
feat(protocol-kit): Add Viem adapter

### PR DESCRIPTION
**Pull request by fdarian**
## What it solves
Resolves https://github.com/safe-global/safe-core-sdk/issues/594

## How this PR fixes it
Created [ViemAdapter](https://github.com/safe-global/safe-core-sdk/blob/7088147d3ed3ac787d58c2d479901349fe369970/packages/protocol-kit/src/adapters/viem/ViemAdapter.ts#L50)

### CODE REVIEW

**Comment by farreldarian** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by d4mr** [comment]
This will be great to have, anything pending to add, or anything we can do to help expedite this?

**Comment by farreldarian** [comment]
Hi @d4mr, I hope to continue on this over the weekend, currently the tests are still failing. Additionally, I might need to check for any change from the AbiType migration (e.g. https://github.com/safe-global/safe-core-sdk/issues/673)

**Comment by farreldarian** [comment]
Update: 10 test failing

```
     AbiFunctionNotFoundError: Function "isValidSignature(bytes32,bytes)" not found on ABI.
Make sure you are using the correct ABI and that the function exists on it.

Docs: https://viem.sh/docs/contract/encodeFunctionData.html
Version: viem@2.0.6
      at encodeFunctionData (/Users/farreldarian/code/safe-global/safe-core-sdk/node_modules/viem/utils/abi/encodeFunctionData.ts:92:22)
      at CompatibilityFallbackHandler_V1_4_1_Viem.encode (src/adapters/viem/ViemContract.ts:2:789)
      at Safe.isValidSignature (src/Safe.ts:41:17)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Context.<anonymous> (tests/e2e/eip1271-contract-signatures.test.ts:292:11)
```

[Need to check](https://github.com/wevm/viem/discussions/1799) on how to specify overloaded function

**Comment by dasanra** [comment]
Thank you for your contribution. Instead of creating an specific adapter we refactored the code to receive an EIP-1193 provider, that way we can support any of the providers using a standard.

**Pull request closed without merging**
