### PR TITLE
Adds Particle Network Auth Kit Pack

### PR DESCRIPTION
**Pull request by TABASCOatw**
## Introduction of Particle Network as a pack within Auth Kit

This pull request adds Particle Network (Particle Wallet-as-a-Service) alongside Web3Auth within Auth Kit.
- New folder, `particle-network` within packs
- ModalPack, `ParticleModalPack` has been created; modeled after the existing Web3Auth modal
- Relevant types have been included in `types`.

Essentially, this enables full utilization of Particle Network within Auth Kit (to the same degree of the other pack, Web3Auth). This has also been reflected in a written (and tested) tutorial currently in a [drafted PR on the Safe Docs](https://github.com/safe-global/safe-docs/pull/264)

All relevant packages, existing documentation pages, and other relevant files have been updated to reflect the addition of Particle Network's Auth Kit pack.

### CODE REVIEW

**Comment by TABASCOatw** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dasanra** [comment]
Hey! Thank you for your PR. Currently we are doing an auth-kit refactor. Once we are done we will review and test your PR.

**Comment by TABASCOatw** [comment]
Hey @dasanra! Just wanted to check in here; is there anything we could do to update this to adhere to any new standards or architecture? Happy to do a bit of a revamp on this PR if you guys are ready for something like that

**Comment by dasanra** [comment]
auth-kit was deprecated 🙏

**Pull request closed without merging**
