### PR TITLE
Added pulsechain mainnet and testnet shortNames to eip-3770 config

### PR DESCRIPTION
**Pull request by 0xtubanator**
## What it solves
Resolves #
Pulsechain mainnet and testnet shortNames are now available in the eip-3770 config

## How this PR fixes it
Just edited the single file

### CODE REVIEW

**Comment by 0xtubanator** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 0xtubanator** [comment]
recheck

**Comment by 0xtubanator** [comment]
Hi @dasanra 

Whenever you get a chance could you please review the PR.

Thanks in advance.

**Comment by dasanra** [comment]
Hey @0xtubanator

We need the new version of `@safe-global/safe-deployments` package to be released before this change can be considered. Once is done we don't need this PR, when updating the library the values will be added.

**Comment by 0xtubanator** [comment]
Thank you for your response.

**Pull request closed without merging**
