### PR TITLE
chore: ethers.js v6 support

### PR DESCRIPTION
**Pull request by germartinez**
## What it solves
Support `ethers.js` `v6.3.0`

Blockers:
- `hardhat` is not supporting `ethers.js` `v6` yet https://github.com/NomicFoundation/hardhat/pull/3924

### CODE REVIEW

**Comment by 0xdeployer** [comment]
Looks like hardhat merged their PR on May 30. When can is be merged ?

**Comment by froggiedev** [comment]
> @germartinez Any estimate on when this will be ready to use ? This is currently a blocker for us to use Safe for account abstraction, as all our codebase is using ethers v6

@dasanra can we get an update on this?

**Comment by dasanra** [comment]
@froggiedev we are currently working on it, we will create a new PR as there are many conflicts in this one. Can't say a specific date but it's our next major change on the `protocol-kit`

**Comment by dasanra** [comment]
Closing. Will be fixed on https://github.com/safe-global/safe-core-sdk/pull/549

**Pull request closed without merging**
