### PR TITLE
add shortname for fxcore and dhobyghaut

### PR DESCRIPTION
**Pull request by lance-web3**
add shortname for fxcore
https://chainlist.org/chain/530

add shortname for dhobyghaut
https://chainlist.org/chain/90001

fxcore 1.4.1 safe deployment
https://github.com/safe-global/safe-deployments/pull/663

dhobyghaut 1.4.1 safe deployment
https://github.com/safe-global/safe-deployments/pull/652

### CODE REVIEW

**Comment by lance-web3** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lance-web3** [comment]
@dasanra Hello, anything is still needed from our side?

**Comment by dasanra** [comment]
@lance-web3 no. This change requires a bump in `@safe-global/safe-deployments` dependency and all the short names for all the new changes should be added at once.

**Comment by lance-web3** [comment]
> @lance-web3 no. This change requires a bump in `@safe-global/safe-deployments` dependency and all the short names for all the new changes should be added at once.

okay sure, need help on this too https://github.com/safe-global/safe-core-sdk/issues/909

**Comment by dasanra** [comment]
Added in #910

**Pull request closed without merging**
