### PR TITLE
Added 5165 short name

### PR DESCRIPTION
**Pull request by fastexlabs**
Added 5165 'ftn' short name

## What it solves
Resolves #

## How this PR fixes it

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by fastexlabs** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fastexlabs** [comment]
recheck

**Comment by SurenFTN** [comment]
@dasanra can you check please

**Comment by dasanra** [comment]
@SurenFTN `@safe-global/safe-deployments` package containing this chain wasn't published yet on npm. It will be automatically updated here when the safe-deployments package is available.

**Comment by SurenFTN** [comment]
@

> @SurenFTN `@safe-global/safe-deployments` package containing this chain wasn't published yet on npm. It will be automatically updated here when the safe-deployments package is available.

Any thought when it will be updated ?

**Comment by dasanra** [comment]
Solved in #1017

We will push Safe Core SDK packages tomorrow.

**Pull request closed without merging**
