### PR TITLE
feat: add EIP-3779 shortname for appchain

### PR DESCRIPTION
**Pull request by emrme**
## What it solves
Resolves #
https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-466.json
https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-4661.json

### CODE REVIEW

**Comment by emrme** [comment]
@akshay-ap @germartinez pls approve

**Comment by emrme** [comment]
@yagopv pls approve

**Comment by emrme** [comment]
@yagopv @DaniSomoza pls approve

**Comment by yagopv** [comment]
Hey @emrme. The config file in this repo is generated from the [safe-deployments](https://github.com/safe-global/safe-deployments) repo

Take a look to this [doc page](https://docs.safe.global/core-api/safe-contracts-deployment#record-your-contracts-in-the-official-registry)

A similar PR should be like [this one](https://github.com/safe-global/safe-deployments/pull/679)

**Comment by emrme** [comment]
Hey @yagopv, my PRs to `safe-deployments` repo are all merged already:

https://github.com/safe-global/safe-deployments/pull/916
https://github.com/safe-global/safe-deployments/pull/915
https://github.com/safe-global/safe-deployments/pull/918
https://github.com/safe-global/safe-deployments/pull/914

So now you are waiting for npm package release I guess?

**Comment by yagopv** [comment]
> So now you are waiting for npm package release I guess?

Yes, this will be included in the next protocol-kit release. Probably next week

**Comment by yagopv** [comment]
Hey @emrme, a new version (v5.1.1) was published containing appchain networks

**Pull request closed without merging**
