### PR TITLE
Fixed example not working

### PR DESCRIPTION
**Pull request by CAPTAIN320**
## What it solves
Resolves #
Example not working by Fixing modules not found error

## How this PR fixes it
Updates to the correct path
Add essential modules from instructions in docs

### CODE REVIEW

**Comment by CAPTAIN320** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by CAPTAIN320** [comment]
recheck

**Comment by yagopv** [comment]
Hey @CAPTAIN320,

First, thank you for the feedback and the PR 🫶🏻

The examples from the onramp-kit and auth-kit should work as they are. The idea for the examples are to: 

1) Use them for local development. For this reason we have the relative deps to the `src/index`
2) Showcase posible usages

I'm using the examples for local development all the time so should work. The steps for using them (auth-kit) are:

```
// In the project root
1) yarn install
2) yarn build

// In the auth-kit example root
3) yarn install
4) Configure `.env` following `.env.sample`
5) yarn start

```

I would appreciate if you test this. 

I'm going to create a PR to the examples README's to show this info.

Thanks!!

**Comment by yagopv** [comment]
Added some help here => https://github.com/safe-global/safe-core-sdk/pull/403/files

**Comment by germartinez** [comment]
I'm closing this PR if there are no more comments.
Feel free to reach out again if the issue persists.

**Pull request closed without merging**
